# Generated by Django 4.1.6 on 2023-07-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200, null=True)),
                ('LastName', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(max_length=200, null=True)),
                ('Category', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=14)),
                ('Situation', models.CharField(choices=[('Very Critical', 'Very Critical'), ('Moderately Critical', 'Moderately Critical'), ('Not Critical', 'Not Critical')], max_length=40, null=True)),
                ('Date', models.DateField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Status', models.CharField(choices=[('Served', 'Served'), ('Not Served', 'Not Served')], default='Not Served', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(max_length=200, null=True)),
                ('Illness', models.CharField(max_length=200, null=True)),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drugs', models.IntegerField(null=True)),
                ('Admitted', models.IntegerField(null=True)),
                ('Emergency', models.IntegerField(null=True)),
            ],
        ),
    ]
