# Generated by Django 4.1.6 on 2023-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_alter_appointment_age_alter_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='Doctors',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='Nurses',
            field=models.IntegerField(null=True),
        ),
    ]
