# Generated by Django 4.1.6 on 2023-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0004_statistic_patients_statistic_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('Served', 'Served'), ('Not Served', 'Not Served')], default='Not Served', max_length=40),
        ),
    ]
